FROM golang:1.22 as builder
ARG GOPROXY=direct
WORKDIR /go/src/ehang.io/nps
COPY . .
RUN go get -d -v ./...
RUN CGO_ENABLED=0 go build -ldflags="-w -s -extldflags -static" ./cmd/nps/nps.go

FROM scratch
COPY --from=builder /go/src/github.com/donetkit/nps-client/nps /
COPY --from=builder /go/src/github.com/donetkit/nps-client/web /web
VOLUME /conf
CMD ["/nps"]
